/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#86a0cd",
        "primary-fixed-dim": "#adc7f7",
        "background": "#f9f9ff",
        "on-tertiary-fixed-variant": "#41474e",
        "on-surface-variant": "#43474e",
        "surface-container-highest": "#d8e3fa",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#dde3eb",
        "primary-container": "#1a365d",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dee8ff",
        "on-tertiary-container": "#989fa6",
        "on-surface": "#111c2c",
        "inverse-primary": "#adc7f7",
        "on-error-container": "#93000a",
        "on-background": "#111c2c",
        "primary": "#002045",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4bd6fa",
        "surface-tint": "#455f88",
        "primary-fixed": "#d6e3ff",
        "tertiary-container": "#30363c",
        "outline": "#74777f",
        "error": "#ba1a1a",
        "on-primary-fixed": "#001b3c",
        "outline-variant": "#c4c6cf",
        "inverse-surface": "#263142",
        "on-error": "#ffffff",
        "tertiary": "#1b2127",
        "secondary-container": "#4fd9fd",
        "tertiary-fixed-dim": "#c1c7cf",
        "surface": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#005c70",
        "on-secondary-fixed": "#001f27",
        "on-primary-fixed-variant": "#2d476f",
        "surface-variant": "#d8e3fa",
        "on-tertiary-fixed": "#161c22",
        "surface-dim": "#cfdaf1",
        "secondary-fixed": "#b2ebff",
        "surface-bright": "#f9f9ff",
        "secondary": "#00677c",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#004e5e",
        "surface-container": "#e7eeff",
        "surface-container-low": "#f0f3ff"
      },
      spacing: {
        "container-max": "1280px",
        "xl": "80px",
        "lg": "48px",
        "sm": "12px",
        "md": "24px",
        "base": "8px",
        "xs": "4px",
        "margin-mobile": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["Noto Sans", "sans-serif"],
        "headline-sm": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Noto Sans", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-sm": ["Noto Sans", "sans-serif"],
        "headline-lg-mobile": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      },
      maxWidth: {
        "container-max": "1280px",
      }
    },
  },
  plugins: [],
}

